export default interface IData {
    people: {
        name: string
    }[];
};
// Generated by https://quicktype.io

export interface MerchantsTypes {
    fullname:                         string;
    business_name:                    string;
    mobile_number:                    string;
    is_test:                          boolean;
    onboarding_stage:                 number;
    business_nuban:                   string;
    business_bvn:                     string;
    status:                           string;
    is_admin:                         boolean;
    has_bank:                         boolean;
    is_email_verified:                boolean;
    is_verified:                      boolean;
    has_accepted_terms_and_condition: null;
    email:                            string;
    token:                            string;
    role:                             string;
    permissions:                      string[];
    product_tour:                     string;
}
